"""Streamlit interface for predicting a 128-step smartphone sensor window."""

from __future__ import annotations

import io
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import streamlit as st
import tensorflow as tf

from src.data import SENSOR_FILES, transform_windows


DEFAULT_ARTIFACT_DIR = Path(__file__).parent / "artifacts"


@st.cache_resource(show_spinner="Loading saved LSTM model...")
def load_artifacts(artifact_dir_text: str):
    """Load model metadata once per selected artifact directory."""
    artifact_dir = Path(artifact_dir_text).expanduser()
    model_path = artifact_dir / "har_lstm.keras"
    scaler_path = artifact_dir / "scaler.joblib"
    labels_path = artifact_dir / "class_names.json"
    missing = [path.name for path in (model_path, scaler_path, labels_path) if not path.is_file()]
    if missing:
        raise FileNotFoundError(
            f"Missing {', '.join(missing)} in {artifact_dir}. Run train.py first or choose its artifacts folder."
        )
    return (
        tf.keras.models.load_model(model_path),
        joblib.load(scaler_path),
        json.loads(labels_path.read_text()),
    )


def coerce_window(array: np.ndarray) -> np.ndarray:
    """Validate and normalize an input window to the expected (1, 128, 9) shape."""
    array = np.asarray(array, dtype=np.float32)
    if array.shape == (1, 128, 9):
        array = array[0]
    if array.shape == (9, 128):
        array = array.T
    if array.shape != (128, 9):
        raise ValueError(
            "Expected one 128-by-9 sensor window (or 9-by-128, which is transposed automatically). "
            f"Received shape {array.shape}."
        )
    if not np.isfinite(array).all():
        raise ValueError("Sensor data contains a missing, infinite, or non-numeric value.")
    return array[np.newaxis, ...]


def uploaded_window(uploaded_file) -> np.ndarray:
    if uploaded_file.name.lower().endswith(".npy"):
        return coerce_window(np.load(io.BytesIO(uploaded_file.getvalue()), allow_pickle=False))
    try:
        return coerce_window(np.loadtxt(io.StringIO(uploaded_file.getvalue().decode("utf-8")), delimiter=","))
    except UnicodeDecodeError as error:
        raise ValueError("CSV input must be UTF-8 text.") from error
    except ValueError as error:
        raise ValueError(
            "Could not parse the CSV. Use comma-separated numeric values with no header."
        ) from error


def main() -> None:
    st.set_page_config(page_title="Human Activity Recognition", page_icon="📱", layout="wide")
    st.title("📱 Human Activity Recognition")
    st.caption("LSTM prediction from a 2.56-second smartphone sensor window (128 readings × 9 channels).")

    with st.sidebar:
        st.header("Model artifacts")
        artifact_dir = st.text_input("Artifacts folder", value=str(DEFAULT_ARTIFACT_DIR))
        st.caption("Generated by `python train.py ...`.")

    try:
        model, scaler, class_names = load_artifacts(artifact_dir)
    except (FileNotFoundError, OSError, ValueError) as error:
        st.error(str(error))
        st.info("Train the model first, then start this app again.")
        return

    selected_source = st.radio("Input source", ["Saved demo window", "Upload a window"], horizontal=True)
    raw_window: np.ndarray | None = None
    actual_label: str | None = None
    if selected_source == "Saved demo window":
        demo_path = Path(artifact_dir).expanduser() / "demo_window.npy"
        demo_label_path = Path(artifact_dir).expanduser() / "demo_window_label.json"
        if not demo_path.is_file():
            st.warning("No saved demo is available. Select Upload a window instead.")
        else:
            raw_window = coerce_window(np.load(demo_path, allow_pickle=False))
            if demo_label_path.is_file():
                actual_label = json.loads(demo_label_path.read_text()).get("true_label")
    else:
        uploaded_file = st.file_uploader("Upload .npy or headerless .csv", type=["npy", "csv"])
        st.caption("Expected columns: " + ", ".join(SENSOR_FILES))
        if uploaded_file is not None:
            try:
                raw_window = uploaded_window(uploaded_file)
            except ValueError as error:
                st.error(str(error))

    if raw_window is None:
        return

    left, right = st.columns([1, 1.4])
    with left:
        if st.button("Predict activity", type="primary", use_container_width=True):
            normalized_window = transform_windows(raw_window, scaler)
            probabilities = model.predict(normalized_window, verbose=0)[0]
            predicted_index = int(np.argmax(probabilities))
            st.success(f"Predicted activity: **{class_names[predicted_index].replace('_', ' ')}**")
            if actual_label:
                st.caption(f"Held-out demo label: {actual_label.replace('_', ' ')}")
            probability_table = pd.DataFrame(
                {"Activity": [name.replace("_", " ") for name in class_names], "Probability": probabilities}
            ).set_index("Activity")
            st.bar_chart(probability_table)
    with right:
        st.subheader("Raw sensor window")
        signal_frame = pd.DataFrame(raw_window[0], columns=SENSOR_FILES)
        st.line_chart(signal_frame, height=340)


if __name__ == "__main__":
    main()
